
    print(e , "I am in exception